CREATE TABLE An2019 (
   id INT NOT NULL AUTO_INCREMENT,
   JUDET VARCHAR(100) NOT NULL,
   CATEGORIE_NATIONALA VARCHAR(200) NOT NULL,
   CATEGORIE_COMUNITARA VARCHAR(200),
   MARCA VARCHAR(100),
  DESCRIERE_COMERCIALA VARCHAR(200),
  TOTAL_VEHICULE INT NOT NULL,
   PRIMARY KEY ( id )
)
